"""empty message

Revision ID: ee80889cd9c0
Revises: 
Create Date: 2025-05-21 13:13:07.837739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee80889cd9c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Enum('ACTIVE', 'CALM', 'CULTURAL', 'FOOD', name='activitytype'), nullable=False),
    sa.Column('climate', sa.Enum('COLD', 'WARM', 'MODERATE', name='climatetype'), nullable=False),
    sa.Column('length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='lengthtype'), nullable=False),
    sa.Column('transport', sa.Enum('PLANE', 'TRAIN', 'CAR', 'SHIP', name='transporttype'), nullable=False),
    sa.Column('budget', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='budgettype'), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
